// <auto-generated />
namespace Catalog.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class navigation_properties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(navigation_properties));
        
        string IMigrationMetadata.Id
        {
            get { return "201801071120362_navigation_properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
