// <auto-generated />
namespace Catalog.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class actionlogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actionlogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201801131806056_action-logs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
